### ISSUE TITLE
Issue with file format

### ISSUE THREAD

**Issue by malonkit** [garethky/glowforge-colorific-fusion360-post#1]
Unable to access postprocessor file on Mac OS.
Specifically, after enabling cloud libraries, I downloaded the glowforge.cps in the Fusion 360 postprocessor library, uploaded to my cloud library, opened the postprocessor dialog window, selected My Cloud Library as source, and the glowforge postprocessor was listed as an option.

I repeated the same steps for the glowforgeColorific.cps from github. While the file was successfully uploaded and appears in my assets/CAMPosts folder, the glowforgeColorific postprocessor is not visible in the Postprocess dialog window.
The autodesk knowledge network points to a probem with the postprocessor file format.
https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/Fusion-360-Post-processor-does-not-appear-in-cloud-library-despite-cloud-libraries-being-turned-on.html

**Comment by johnboiles** [comment]
I know this is old, and maybe no longer an issue (@malonkit please close if so), but for me, I had to restart Fusion360 after adding the post-processor to my `assets/CAMPosts` folder. After that, it worked fine.

**Comment by garethky** [comment]
There is now a management dialog in Fusion 360 that allows you to both add and delete custom Posts without having to find the local folder where they are stored. This should be resolved now that Fusions has made those updates.

Either way I'm going to close this as this as a bug against Fusion 360 itself.
