### ISSUE TITLE
Free version of Fusion360 now shows travel moves in generated SVG

### ISSUE THREAD

**Issue by johnboiles** [garethky/glowforge-colorific-fusion360-post#2]
Within the last week, it appears that something has changed (probably a new version of Fusion360) which causes this post-processor to now include travel moves. Heres an exported SVG from today

![image](https://user-images.githubusercontent.com/218876/95024926-eda7d080-063a-11eb-8c58-7824b8e40e37.png)

And here's the exact same Fusion Setup generated on Sep 29 (5 days ago):

![image](https://user-images.githubusercontent.com/218876/95024962-1a5be800-063b-11eb-9198-5f2d9689d346.png)

I might be able to look into this but @garethky if you have any immediate thoughts I'd appreciate your guidance!

**Comment by johnboiles** [comment]
Here's another design, for example

![image](https://user-images.githubusercontent.com/218876/95025122-6b201080-063c-11eb-9198-a463fc98f3d8.png)
![image](https://user-images.githubusercontent.com/218876/95025135-87bc4880-063c-11eb-8539-535bc54342bb.png)

**Comment by johnboiles** [comment]
Based on a quick look at the [code](https://github.com/garethky/glowforge-colorific-fusion360-post/blob/master/GlowforgeColorific.cps#L441), it seems like Fusion must be passing in `MOVEMENT_CUTTING`, `MOVEMENT_REDUCED`, or `MOVEMENT_FINISH_CUTTING` as the movement type for travels, otherwise those lines wouldn't render. So seems very possible this is a Fusion360 bug.

**Comment by johnboiles** [comment]
I exported the same setup with my GRBL post-processor and I see this exported in the file: 🤦 

```
(When using Fusion 360 for Personal Use, the feedrate of rapid moves is reduced to match the feedrate of cutting moves, which can increase machining time. Unrestricted rapid moves are available with a Fusion 360 Subscription.)
(Operation 1 of 3 : 2D Profile2)
```

So Autodesk has intentionally made this annoying :(

**Comment by garethky** [comment]
AutoDesk said they would remove rapid moves from the unpaid version of Fusion 360. So its likely this has broken the post processor. Possibly the laser off state can be detected by looking for another command (laser off/laser on) and tracking that state to detect travel moves. I'll need to do a deeper investigation of the new output to see.

**Comment by johnboiles** [comment]
Yeah that's super annoying. I guess If they differentiated which moves were travel moves vs which moves were cutting moves then it would be trivial for post-processors to just use a rapid move for any travel move.

Rapid moves seems like such a weird feature to limit -- post-processors could hack around it anyways (by doing things like using rapid moves above a certain Z height or like you say, using rapid moves when the tool is off).

Also I made a forum post about it: https://forums.autodesk.com/t5/fusion-360-manufacture/removal-of-rapid-moves-breaks-glowforge-post-processor/m-p/9783371

**Comment by garethky** [comment]
They do set the laser to off/on so we can detect what is meant to be cut vs what is not a cutting move that way. This change fixes the issue in the test suite and in the simple tests I tried in the new version of Fusion 360: https://github.com/garethky/glowforge-colorific-fusion360-post/commit/43634dc87e5477fef40ad90f719ca24724c32eb3

Master branch has been updated with the fix. Please test and verify that things are working as before.

**Comment by johnboiles** [comment]
You're a champ @garethky! I'll try it out

**Comment by johnboiles** [comment]
Works for me locally!

![image](https://user-images.githubusercontent.com/218876/95030264-78042a80-0663-11eb-8329-143a0a4af60f.png)

I had to restart Fusion360 after replacing the file in Assets/CAMPosts before it would take effect in my Cloud Posts. It worked right away in my 'Personal Posts' (`~/Autodesk/Fusion\ 360\ CAM/Posts`)

**Comment by johnboiles** [comment]
Thanks again for the quick fix!

**Comment by garethky** [comment]
Thanks for the bug report!
